// DemoBro "Did you know?" fact pool — shown while a demo renders.
// 50 vetted, real tech-history facts.
export const DEMOBRO_FACTS: string[] = [
  "The world's first webcam watched a coffee pot at Cambridge in 1991 — so no one would walk over to find it empty.",
  "The word \"bug\" for a glitch predates computers. Edison used it in an 1878 letter.",
  "IBM's 1956 RAMAC was the first computer with a hard drive. It stored 5MB and was the size of two refrigerators.",
  "The @ symbol was nearly forgotten until Ray Tomlinson picked it for email addresses in 1971.",
  "Ada Lovelace wrote the first algorithm in 1843 — a century before the first computer existed.",
  "The first computer mouse, built by Doug Engelbart in the 1960s, was carved out of wood.",
  "The first message sent over ARPANET in 1969 was meant to be \"LOGIN.\" It crashed after \"LO.\"",
  "Email is older than the web. Email showed up in 1971; the World Wide Web arrived around 1991.",
  "The first item ever sold on eBay (1995) was a broken laser pointer. On purpose.",
  "\"Spam\" for junk messages comes from a Monty Python sketch about a cafe that served Spam with everything.",
  "Nintendo was founded in 1889 — as a playing card company.",
  "The first YouTube video, \"Me at the zoo,\" went up in 2005 and is still online.",
  "Wi-Fi doesn't stand for anything. \"Wireless Fidelity\" was invented by marketers after the name was chosen.",
  "Google was originally called \"BackRub.\"",
  "The first domain name ever registered was Symbolics.com, back in 1985.",
  "The first PC virus, \"Brain\" (1986), included the creators' real names, address, and phone number.",
  "The Firefox logo isn't a fox — it's a red panda.",
  "Amazon was almost named \"Cadabra,\" until a lawyer misheard it as \"cadaver.\"",
  "The \"save\" icon is a floppy disk — a thing most people under 25 have never touched.",
  "The first video game, \"Spacewar!\", was built in 1962 on a computer the size of a room.",
  "Your phone has far more computing power than all of NASA had for the 1969 moon landing.",
  "The smiley emoticon :-) was proposed by Scott Fahlman in 1982 to mark jokes online.",
  "Python the language is named after Monty Python, not the snake.",
  "Bluetooth is named after a 10th-century Danish king. Its logo is his initials in Norse runes.",
  "The very first web page is still live at info.cern.ch.",
  "Nokia started in 1865 — as a paper mill.",
  "The first text message, sent in 1992, simply said \"Merry Christmas.\"",
  "There are more possible chess games than there are atoms in the observable universe.",
  "The programming language Ada is named after Ada Lovelace, the first programmer.",
  "Linus Torvalds announced Linux in 1991 as a hobby that \"won't be big and professional.\"",
  "JavaScript was created in just 10 days in 1995.",
  "JavaScript has almost nothing to do with Java. The name was pure marketing.",
  "\"Robot\" comes from a 1920 Czech play — from a word meaning \"forced labor.\"",
  "The Konami Code — up, up, down, down, left, right, left, right, B, A — first appeared in 1986.",
  "The creator of the GIF insists it's pronounced \"jif.\" The internet disagrees.",
  "The first digital camera (Kodak, 1975) took 23 seconds to save a single photo to a cassette tape.",
  "Apple's first logo showed Isaac Newton under a tree — no rainbow apple in sight.",
  "The original 2007 iPhone couldn't record video, copy-paste, or run third-party apps.",
  "The programmer's favorite placeholder, \"foobar,\" likely traces back to WWII-era slang.",
  "Google's founders reportedly tried to sell the company in 1999 for under $1M. The buyer passed.",
  "HP got its start in a rented Palo Alto garage in 1939 — now considered the birthplace of Silicon Valley.",
  "The first banner ad (1994) had a click-through rate of 44%. Today's average is under 0.1%.",
  "CAPTCHA is an acronym ending in \"Telling Computers and Humans Apart.\"",
  "The first tweet was posted by Jack Dorsey in March 2006: \"just setting up my twttr.\"",
  "Most of the world's money exists only as numbers on computers — never as physical cash.",
  "QWERTY was designed in the 1870s for mechanical typewriters, and we've never let it go.",
  "The first 1GB-class storage systems in the early '80s weighed hundreds of pounds and cost a fortune.",
  "A team at MIT coined \"hacker\" in the 1960s — it meant a clever, elegant solution, not a criminal.",
  "The USB symbol is shaped like Neptune's trident, hinting you can plug into anything.",
  "Right now, a headless browser is clicking through your site like a caffeinated intern. Hang tight.",
];
